# login node: mngx-blyris-slurm-login-01
name = "Rachel"
scheduler = "slurm"

install_path = "./install"
output_path = "./results"
default_partition = "gb200-blyris"

gpus_per_node = 4
ntasks_per_node = 4

cache_docker_images_locally = false

distribution = "block"
extra_sbatch_args = ["--segment 1"]

[[partitions]]
name = "gb200-blyris"

[global_env_vars]
# NCCL General Configuration
NCCL_SOCKET_IFNAME = "enP5p9s0"

# NCCL Specific Configurations
NCCL_IB_ADAPTIVE_ROUTING = "1"
NCCL_IB_QPS_PER_CONNECTION = "1"
NCCL_IB_SPLIT_DATA_ON_QPS = "0"
NCCL_IBEXT_DISABLE = "0"

MASTER_ADDR = "$SLURM_JOB_MASTER_NODE"
MASTER_PORT = "6000"

# Device Visibility Configuration
MELLANOX_VISIBLE_DEVICES = "0,1,2,3"
CUDA_VISIBLE_DEVICES = "0,1,2,3"
GLOO_SOCKET_IFNAME = "enP5p9s0"
HYDRA_FULL_ERROR = "1"

# PyTorch world rank
RANK = "$SLURM_PROCID"
WORLD_SIZE = "$SLURM_NTASKS"
LOCAL_RANK = "$SLURM_LOCALID"
